# Generated by Django 2.2.7 on 2019-11-13 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20191113_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfIntro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='self_image/')),
            ],
        ),
    ]
