# Generated by Django 2.2.7 on 2019-11-13 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_selfintro'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SelfIntro',
            new_name='Intro',
        ),
    ]
