# Generated by Django 2.2.7 on 2019-11-13 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20191113_1056'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
