# Generated by Django 2.2.7 on 2019-11-19 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_delete_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Intro',
        ),
    ]
