# Generated by Django 2.2.7 on 2019-11-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.FilePathField(default='default', path='/img'),
            preserve_default=False,
        ),
    ]
